#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Alien-Build-Plugin-Download-GitLab
Version  : 0.01
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/Alien-Build-Plugin-Download-GitLab-0.01.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/Alien-Build-Plugin-Download-GitLab-0.01.tar.gz
Summary  : 'Alien::Build plugin to download from GitLab'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Alien-Build-Plugin-Download-GitLab-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Alien::Build::Plugin)
BuildRequires : perl(Importer)
BuildRequires : perl(Path::Tiny)
BuildRequires : perl(Sub::Info)
BuildRequires : perl(Test2::V0)
BuildRequires : perl(URI)
BuildRequires : perl(URI::Escape)

%description
NAME
Alien::Build::Plugin::Download::GitLab - Alien::Build plugin to
download from GitLab

%package dev
Summary: dev components for the perl-Alien-Build-Plugin-Download-GitLab package.
Group: Development
Provides: perl-Alien-Build-Plugin-Download-GitLab-devel = %{version}-%{release}
Requires: perl-Alien-Build-Plugin-Download-GitLab = %{version}-%{release}

%description dev
dev components for the perl-Alien-Build-Plugin-Download-GitLab package.


%package perl
Summary: perl components for the perl-Alien-Build-Plugin-Download-GitLab package.
Group: Default
Requires: perl-Alien-Build-Plugin-Download-GitLab = %{version}-%{release}

%description perl
perl components for the perl-Alien-Build-Plugin-Download-GitLab package.


%prep
%setup -q -n Alien-Build-Plugin-Download-GitLab-0.01
cd %{_builddir}/Alien-Build-Plugin-Download-GitLab-0.01

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Alien::Build::Plugin::Download::GitLab.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
